version: '3'

services:

  nginx:
    image: nginx
    container_name: backend_nginx
    ports:
      - 1337:1337
    restart: always
    volumes:
      - ./helper/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
      - ./logs/:/var/log/nginx
    depends_on:
      - web
    networks:
      main:
          aliases:
              - nginx

  postgres:
    restart: always
    image: postgres:10
    container_name: backend_postgres
    env_file: .env
    networks:
      main:
        aliases:
          - postgres

  redis:
    image: 'bitnami/redis:latest'
    container_name: backend_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      main:
        aliases:
          - redis

  web:
    image: registry.gitlab.com/awesomeradio/backend:latest
    build:
      context: .
    container_name: backend_web
    ports:
        - "8000:8000"
    command: sh -c 'until nc -z postgres 5432; do echo "Waiting for Postgres...";done;python manage.py migrate --noinput && ./helper/superuser.sh && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application -w 2 -b :8000 --capture-output --log-level=info'
    depends_on:
      - postgres
    volumes:
      - static_volume:/project/static
      - media_volume:/project/media
    env_file: .env
    links:
      - postgres
    networks:
        main:
            aliases:
                - web

networks:
  main:

volumes:
  static_volume:
  media_volume: