version: '3'

services:

  nginx:
    image: nginx
    ports:
      - 1337:1337
    restart: always
    volumes:
      - ./helper/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./logs/:/var/log/nginx
    depends_on:
      - web
    networks:
      main:
          aliases:
              - nginx
  postgres:
    restart: always
    image: postgres:10
    container_name: postgres
    env_file: .env
    networks:
      main:
        aliases:
          - postgres

  web:
    image: registry.gitlab.com/awesomeradio/backend:latest
    build:
      context: .
    container_name: web
    ports:
        - "8000:8000"
    command: bash -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application -w 2 -b :8000 --capture-output --log-level=info'
    depends_on:
      - postgres
    volumes:
      - ./static:/static
      - ./media:/media/
    env_file: .env
    links:
      - postgres
    networks:
        main:
            aliases:
                - web



networks:
  main:
