# Generated by Django 3.0.6 on 2020-05-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, default=0, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
