# Generated by Django 3.0.6 on 2020-05-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20200531_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(blank=True, max_length=2048, null=True)),
                ('value', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='channels.ChannelSet'),
        ),
    ]
