# Generated by Django 3.0.6 on 2020-05-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20200531_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelparameter',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='channels.Channel'),
        ),
    ]
