# Generated by Django 3.0.6 on 2020-05-31 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channelparameter_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='media_file',
        ),
        migrations.CreateModel(
            name='ChannelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='channels.Channel')),
            ],
        ),
    ]
