# Generated by Django 3.0.6 on 2020-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20200531_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='frequency',
            new_name='from_frequency',
        ),
        migrations.AddField(
            model_name='channel',
            name='to_frequency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
