# Generated by Django 3.0.6 on 2020-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20200531_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
